name: Albert Camps Llad√≥
markdown: redcarpet
pygments: true
encoding: utf-8
paginate: 5
paginate_path: "blog/page:num"

post:
  template: _post.txt
  extension: markdown
page:
  template: _page.txt
  extension: markdown
editor: vim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Documents/Projects/acamps.github.io/
